name: build-macos-arm64-boringtron

on:
  workflow_dispatch:
  push:
    branches: [ boring-current ]

jobs:
  checkout-macos:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/electron/build:cf814a4d2501e8e843caea071a6b70a48e78b855
      options: --user root
    env:
      GCLIENT_EXTRA_ARGS: '--custom-var=checkout_mac=True --custom-var=host_os=mac'
    outputs:
      build-image-sha: cf814a4d2501e8e843caea071a6b70a48e78b855
    steps:
      - uses: actions/checkout@v4
        with:
          path: src/electron
          fetch-depth: 0
      - name: Checkout & Sync deps
        uses: ./src/electron/.github/actions/checkout

  macos-arm64:
    permissions:
      contents: read
      issues: read
      pull-requests: read
    needs: checkout-macos
    uses: ./.github/workflows/pipeline-electron-build-and-test.yml
    with:
      build-runs-on: macos-14
      test-runs-on:  macos-14
      target-platform: macos
      target-arch: arm64
      is-release: false
      gn-build-type: testing
      generate-symbols: false
      upload-to-storage: '0'
    secrets: inherit
